// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaizesDoNordeste.Infrastructure.DataAccess;

#nullable disable

namespace RaizesDoNordeste.Infrastructure.Migrations
{
    [DbContext(typeof(RaizesDoNordesteDbContext))]
    [Migration("20260529230435_SeedDeUsuarios")]
    partial class SeedDeUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Estoque");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            UnidadeId = 1
                        },
                        new
                        {
                            Id = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            UnidadeId = 2
                        },
                        new
                        {
                            Id = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            UnidadeId = 3
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstoqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensEstoque", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("24230b66-c6fa-4d7b-9d28-5eb6897928f6"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 1,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = new Guid("226acdbd-1743-4c44-8275-b816c8ee2b5b"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 2,
                            Quantidade = 6
                        },
                        new
                        {
                            Id = new Guid("c033df3d-bc83-4be5-8992-2662af1b8520"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 3,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = new Guid("7193fc9c-988f-400f-9cc3-06b26f2ac49d"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 4,
                            Quantidade = 11
                        },
                        new
                        {
                            Id = new Guid("4661f17b-4781-4f8e-a80f-8095b901b787"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 5,
                            Quantidade = 6
                        },
                        new
                        {
                            Id = new Guid("0ae75959-96a8-4294-908a-eb277eec9567"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 9,
                            Quantidade = 6
                        },
                        new
                        {
                            Id = new Guid("b41e8335-2786-4a92-9ad4-bc1af6275916"),
                            EstoqueId = new Guid("1ebb40fa-ea6e-444f-813d-d1251fd052bf"),
                            ProdutoId = 10,
                            Quantidade = 15
                        },
                        new
                        {
                            Id = new Guid("15915bce-5ac2-4502-9ef4-95b60cd307f2"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 1,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = new Guid("cbc73a05-9c04-48c4-bf94-1676ff93fd2e"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 2,
                            Quantidade = 15
                        },
                        new
                        {
                            Id = new Guid("dbc5458b-b3ca-48af-b917-cdde604250f9"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 3,
                            Quantidade = 11
                        },
                        new
                        {
                            Id = new Guid("65ec4b5c-c88d-424f-8f2c-ee9d95e39df6"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 8,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = new Guid("b6e2e780-f78d-4bfa-9d7f-d5811f770665"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 9,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = new Guid("054919e4-56b1-42c2-b6b8-87ba307a3151"),
                            EstoqueId = new Guid("28efd76e-2df0-4eff-8618-c31750451536"),
                            ProdutoId = 10,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = new Guid("1640f03c-a718-4a61-80f1-b92979814b4b"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 3,
                            Quantidade = 16
                        },
                        new
                        {
                            Id = new Guid("20fc78bd-fa0e-4b7d-8aaf-1016b44672ce"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 4,
                            Quantidade = 8
                        },
                        new
                        {
                            Id = new Guid("7a38cf98-3183-4b79-8aa6-c19fd2661b4f"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 5,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = new Guid("94ce378e-8946-4613-a121-3f2af9815aae"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 6,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = new Guid("c1c00c28-e68d-4475-97af-7004f81f3b6e"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 7,
                            Quantidade = 14
                        },
                        new
                        {
                            Id = new Guid("58256543-ab3b-4ef5-8ce1-5fbd7e5b7206"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 8,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = new Guid("5d364e6e-cd1a-4625-9ee5-e6934adf934e"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 9,
                            Quantidade = 18
                        },
                        new
                        {
                            Id = new Guid("4cfac063-6c5f-4470-97a4-bd908278ef94"),
                            EstoqueId = new Guid("7e740bdc-9054-4af1-aaf8-b3ed850b7fed"),
                            ProdutoId = 10,
                            Quantidade = 20
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido", (string)null);
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanalPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaDePagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de camarão",
                            Preco = 29.5m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de carne sol",
                            Preco = 25.0m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de carne seca",
                            Preco = 27.5m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Com chocolate",
                            Nome = "Tapioca com chocolate",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Com doce de leite",
                            Nome = "Tapioca com doce leite",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Com queijo",
                            Nome = "Tapioca de queijo",
                            Preco = 12.0m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Garrafa 2L",
                            Nome = "Coca-cola",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Garrafa 2L",
                            Nome = "Pepsi",
                            Preco = 9.5m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Garrafa 500ML",
                            Nome = "Suco laranja",
                            Preco = 8.0m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Porção de 500GR",
                            Nome = "Porção de queijo coalho",
                            Preco = 30.0m
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Unidade Centro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Unidade Cabral"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Unidade Portão"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73396d14-99c3-49fc-b1ce-b052e5e5c50d"),
                            Email = "cliente@email.com",
                            Nome = "Cliente",
                            Role = 0,
                            Senha = "$2a$11$bAuOcT03JZKfYVZQ.lj5Ne8E06SrGLnghArbkEnc25s1hEJh6SLnq",
                            Sobrenome = "Cliente"
                        },
                        new
                        {
                            Id = new Guid("bea1c218-b855-4ca8-8358-6da9cb59f590"),
                            Email = "atendente@email.com",
                            Nome = "Atendente",
                            Role = 1,
                            Senha = "$2a$11$bAuOcT03JZKfYVZQ.lj5Ne8E06SrGLnghArbkEnc25s1hEJh6SLnq",
                            Sobrenome = "Atendente"
                        },
                        new
                        {
                            Id = new Guid("fc27019d-bbc4-45d5-b6c0-cf91d10828f5"),
                            Email = "cozinha@email.com",
                            Nome = "Cozinha",
                            Role = 2,
                            Senha = "$2a$11$bAuOcT03JZKfYVZQ.lj5Ne8E06SrGLnghArbkEnc25s1hEJh6SLnq",
                            Sobrenome = "Cozinha"
                        },
                        new
                        {
                            Id = new Guid("99311212-2878-42c4-b5c4-6a2f79d3833d"),
                            Email = "gerente@email.com",
                            Nome = "Gerente",
                            Role = 3,
                            Senha = "$2a$11$bAuOcT03JZKfYVZQ.lj5Ne8E06SrGLnghArbkEnc25s1hEJh6SLnq",
                            Sobrenome = "Gerente"
                        },
                        new
                        {
                            Id = new Guid("ce08874a-8df3-4abe-abd6-587c22630cb1"),
                            Email = "admin@email.com",
                            Nome = "Administrador",
                            Role = 4,
                            Senha = "$2a$11$bAuOcT03JZKfYVZQ.lj5Ne8E06SrGLnghArbkEnc25s1hEJh6SLnq",
                            Sobrenome = "Administrador"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Produto", null)
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId");

                    b.HasOne("RaizesDoNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithOne("Estoque")
                        .HasForeignKey("RaizesDoNordeste.Domain.Entities.Estoque", "UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RaizesDoNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesDoNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Estoques");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Estoque")
                        .IsRequired();

                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
