// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaizesDoNordeste.Infrastructure.DataAccess;

#nullable disable

namespace RaizesDoNordeste.Infrastructure.Migrations
{
    [DbContext(typeof(RaizesDoNordesteDbContext))]
    [Migration("20260522232248_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstoqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensEstoque", (string)null);
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de camarão",
                            Preco = 29.5m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de carne sol",
                            Preco = 25.0m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Com requeijão cremoso",
                            Nome = "Cuscuz de carne seca",
                            Preco = 27.5m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Com chocolate",
                            Nome = "Tapioca com chocolate",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Com doce de leite",
                            Nome = "Tapioca com doce leite",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Com queijo",
                            Nome = "Tapioca de queijo",
                            Preco = 12.0m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Garrafa 2L",
                            Nome = "Coca-cola",
                            Preco = 10.0m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Garrafa 2L",
                            Nome = "Pepsi",
                            Preco = 9.5m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Garrafa 500ML",
                            Nome = "Suco laranja",
                            Preco = 8.0m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Porção de 500GR",
                            Nome = "Porção de queijo coalho",
                            Preco = 30.0m
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Unidade Centro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Unidade Cabral"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Unidade Portão"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Unidade", null)
                        .WithOne("Estoque")
                        .HasForeignKey("RaizesDoNordeste.Domain.Entities.Estoque", "UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesDoNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Estoque")
                        .IsRequired();

                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
