//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaizesDoNordeste.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensDeErro {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensDeErro() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RaizesDoNordeste.Exceptions.MensagensDeErro", typeof(MensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        public static string SOBRENOME_VAZIO {
            get {
                return ResourceManager.GetString("SOBRENOME_VAZIO", resourceCulture);
            }
        }
        
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        public static string REFRESH_TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        public static string UNIDADE_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("UNIDADE_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        public static string CANAL_PEDIDO_VAZIO {
            get {
                return ResourceManager.GetString("CANAL_PEDIDO_VAZIO", resourceCulture);
            }
        }
        
        public static string PEDIDO_SEM_ITENS {
            get {
                return ResourceManager.GetString("PEDIDO_SEM_ITENS", resourceCulture);
            }
        }
        
        public static string ESTOQUE_INSUFICIENTE {
            get {
                return ResourceManager.GetString("ESTOQUE_INSUFICIENTE", resourceCulture);
            }
        }
        
        public static string CANAL_PEDIDO_INVALIDO {
            get {
                return ResourceManager.GetString("CANAL_PEDIDO_INVALIDO", resourceCulture);
            }
        }
        
        public static string PRODUTO_NAO_DISPONIVEL {
            get {
                return ResourceManager.GetString("PRODUTO_NAO_DISPONIVEL", resourceCulture);
            }
        }
        
        public static string PRODUTO_ID_INVALIDO {
            get {
                return ResourceManager.GetString("PRODUTO_ID_INVALIDO", resourceCulture);
            }
        }
        
        public static string QUANTIDADE_INVALIDA {
            get {
                return ResourceManager.GetString("QUANTIDADE_INVALIDA", resourceCulture);
            }
        }
        
        public static string PEDIDO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("PEDIDO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        public static string PAGAMENTO_NAO_PODE_SER_PROCESSADO {
            get {
                return ResourceManager.GetString("PAGAMENTO_NAO_PODE_SER_PROCESSADO", resourceCulture);
            }
        }
        
        public static string STATUS_DO_PAGAMENTO_VAZIO {
            get {
                return ResourceManager.GetString("STATUS_DO_PAGAMENTO_VAZIO", resourceCulture);
            }
        }
        
        public static string STATUS_DO_PAGAMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_DO_PAGAMENTO_INVALIDO", resourceCulture);
            }
        }
        
        public static string FORMA_DE_PAGAMENTO_VAZIA {
            get {
                return ResourceManager.GetString("FORMA_DE_PAGAMENTO_VAZIA", resourceCulture);
            }
        }
        
        public static string OPERACAO_NAO_PERMITIDA {
            get {
                return ResourceManager.GetString("OPERACAO_NAO_PERMITIDA", resourceCulture);
            }
        }
        
        public static string STATUS_DO_PEDIDO_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_DO_PEDIDO_INVALIDO", resourceCulture);
            }
        }
        
        public static string STATUS_DO_PEDIDO_VAZIO {
            get {
                return ResourceManager.GetString("STATUS_DO_PEDIDO_VAZIO", resourceCulture);
            }
        }
    }
}
